### ISSUE TITLE
Kernel bug detected[#1]:

### ISSUE THREAD

**Issue by fengfeng0328** [redchenjs/mt76x8-wm8960#1]
root@LEDE:~# speaker-test 

speaker-test 1.1.0

Playback device is default
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
Rate set to 48000Hz (requested 4[  297.218920] Kernel bug detected[#1]:
[  297.223178] CPU: 0 PID: 1376 Comm: speaker-test Not tainted 4.4.124 #0
[  297.229800] task: 81aac000 ti: 80eac000 task.ti: 80eac000
[  297.235271] $ 0   : 00000000 00000001 00000002 00000002
[  297.240587] $ 4   : 818c0e00 8099eec8 8099eec8 00020000
[  297.245896] $ 8   : 00000018 80008c98 77758000 00001000
[  297.251205] $12   : 00022000 00100000 fffffffc 00020000
[  297.256514] $16   : 818c0e00 00000008 80e75780 808d2180
[  297.261820] $20   : 775b6000 775d6000 00000000 00000020
[  297.267129] $24   : 00001072 776e2e00                  
[  297.272437] $28   : 80eac000 80eaddf8 00000000 80232084
[  297.277746] Hi    : 00000000
[  297.280662] Lo    : 00000020
[  297.283600] epc   : 80231f94 snd_pcm_lib_default_mmap+0x30/0x48
[  297.289605] ra    : 80232084 snd_pcm_mmap_data+0xd8/0x124
[  297.295075] Status: 1100e403 KERNEL EXL IE 
[  297.299328] Cause : 10800024 (ExcCode 09)
[  297.303392] PrId  : 00019655 (MIPS 24KEc)
[  297.307452] Modules linked in: pppoe ppp_async iptable_nat pppox ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_Mn
[  297.379945] Process speaker-test (pid: 1376, threadinf+-----------------------------+7777fd48)
[  297.388671] Stack : 775b6000 775d6000 00000000 0000000|                             |020000
          80e75780 00020000 000000fb 00000000 80e75780 00|  Cannot open /dev/ttyUSB0!  |
          00000020 80470000 00000001 8099e528 8099ed80 80|                             |
          80e75780 00020000 00000001 00000002 00000000 00+-----------------------------+
          77778234 0000000b 81aac000 81aac030 00000000 80daede0 808d21b4 80e75780
          ...
[  297.424781] Call Trace:
[  297.427266] [<80231f94>] snd_pcm_lib_default_mmap+0x30/0x48
[  297.432922] [<80232084>] snd_pcm_mmap_data+0xd8/0x124
[  297.438071] [<800995a0>] mmap_region+0x29c/0x544
] SyS_mmap_pgoff+0x8c/0xd8] do_mmap+0x358/0x3d4
[  297.456585] [<8000686c>] syscall_common+0x30/0x54
[  297.461351] 
[  297.462859] 
Code: 24020002  14620002  00000000 <000c000d> 3c02803e  24422e88  aca20048  03e00008  00001021 
8000Hz)
Buffer [  297.473078] ---[ end trace 20464ba028fdbc77 ]---
size range from 2048 to 32768
P[  297.481738] Fatal exception: panic in 5 secondseriod size range from 1024 to 2048
Using max buffer size 32768
Periods = 4

**Comment by redchenjs** [comment]
@chen-zifeng Hi chen-zifeng, this driver can only run on kernel 4.9 or later, the ASoC structure in kernel 4.4 is incompatible with kernel 4.9+
