### ISSUE TITLE
mono sound fault

### ISSUE THREAD

**Issue by PolyLin** [redchenjs/mt76x8-wm8960#10]
hi， @redchenjs , 我在linux-4.14.95上使用了你提供的这个path文件(999-ralink-i2s-mono-sound.zip)，发现在使用ffmpeg播放单声道的时候声音不正常(ffmpeg -v debug -re -i notfound.wav -ar 8000 -ac 1 -f alsa hw:0), 使用双声道播放(-ac 2)就正常了。请问是不是在4.14的kernel上还需要做什么修改？或者是其他的原因？

_Originally posted by @PolyLin in https://github.com/redchenjs/mt762x-wm8960/issues/7#issuecomment-883184210_

**Comment by redchenjs** [comment]
这个patch只是测试用的，只测试过aplay，可能不完善，可以试试这个帖子的方法：[OpenWrt Forum](https://forum.openwrt.org/t/how-to-config-chan-alsa-in-openwrt-for-mt7628/95084)

**Comment by PolyLin** [comment]
> 这个patch只是测试用的，只测试过aplay，可能不完善，可以试试这个帖子的方法：[OpenWrt Forum](https://forum.openwrt.org/t/how-to-config-chan-alsa-in-openwrt-for-mt7628/95084)

按照论坛帖子的方法测试了下，可以了，谢谢。 
BTW:最好能更新下github上的asound.conf的参考配置，彻底解决下这个问题。
