### ISSUE TITLE
Change I2S clock speed

### ISSUE THREAD

**Issue by huybk213** [redchenjs/mt76x8-wm8960#14]
Dear Redchenjs,

Thanks for your good code,  i have a question about i2s clock.
System only show clock of i2s ~ 480khz, how can i increase?
Thank you

`.i2c /dev entries driver
[    9.539208] gdma-rt2880 10002800.gdma: revision: 3, channels: 16

[    9.576443] i2c-mt7621 10000900.i2c: clock 100KHz, re-start not support

[    9.603849] ralink-i2s 10000a00.i2s: mclk 480KHz   ->>>>>>>>>>>>>>>>>>>>>>>>>>>>>> HERE

[    9.632978] mt762x-wm8960 sound: wm8960-hifi <-> 10000a00.i2s mapping ok

[    9.646364] mt762x-wm8960 sound: ASoC: no sink widget found for Speaker

[    9.659478] mt762x-wm8960 sound: ASoC: Failed to add route SPK_LN -> direct -> Speaker

[    9.675167] mt762x-wm8960 sound: ASoC: no sink widget found for Speaker

[    9.688274] mt762x-wm8960 sound: ASoC: Failed to add route SPK_LP -> direct -> Speaker

[    9.703964] mt762x-wm8960 sound: ASoC: no sink widget found for Speaker

[    9.717070] mt762x-wm8960 sound: ASoC: Failed to add route SPK_RN -> direct -> Speaker

[    9.732758] mt762x-wm8960 sound: ASoC: no sink widget found for Speaker

[    9.745863] mt762x-wm8960 sound: ASoC: Failed to add route SPK_RP -> direct -> Speaker

[    9.761554] mt762x-wm8960 sound: ASoC: no sink widget found for Microphone

[    9.775174] mt762x-wm8960 sound: ASoC: Failed to add route MICB -> direct -> Microphone

[    9.791036] mt762x-wm8960 sound: ASoC: no source widget found for Microphone

[    9.805001] mt762x-wm8960 sound: ASoC: Failed to add route Microphone -> direct -> LINPUT1`

**Comment by redchenjs** [comment]
Hi @huybk213, `480 kHz` is just a typo, it is fixed in [this patch](https://github.com/openwrt/openwrt/blob/21d02e598a0bf209cebc1c5b8f3e433913329107/target/linux/ramips/patches-5.10/835-asoc-add-mt7620-support.patch#L993). Now the `dmesg` will show `480 MHz` instead.

Note that `480 MHz` is only the internal clock used by the I2S hardware, not the `REFCLK` output. The `REFCLK` is always `12 MHz`.

**Comment by huybk213** [comment]
Tks @redchenjs
