### ISSUE TITLE
MCLK && Master or slave

### ISSUE THREAD

**Issue by fengfeng0328** [redchenjs/mt76x8-wm8960#2]
can you tell me the MCLK and wm8960 is use master or slave?

**Comment by redchenjs** [comment]
> 
        .dai_fmt = SND_SOC_DAIFMT_I2S | SND_SOC_DAIFMT_NB_NF | SND_SOC_DAIFMT_CBS_CFS,
>refclk {
        ralink,group = "refclk";
        ralink,function = "refclk";
 };

WM8960 is slave and it can get MCLK from chip's `refclk` pin, ~12MHz
