### ISSUE TITLE
openwrt 19.07.0 内核 4.14.162

### ISSUE THREAD

**Issue by yqboy** [redchenjs/mt76x8-wm8960#4]
这份 并不能 编译成功,但是发现 老哥你在 openwrt 的git 上留下的补丁 
https://github.com/openwrt/openwrt/pull/2413/files
编译是正常的,还是不能 用

![截屏2020-07-04上午1 55 53](https://user-images.githubusercontent.com/19944861/86490325-95420800-bd99-11ea-87b2-9b081b37592a.png)
![截屏2020-07-05下午10 00 06](https://user-images.githubusercontent.com/19944861/86534417-e4f41100-bf0a-11ea-8017-713e877d9097.png)

![截屏2020-07-05下午10 01 30](https://user-images.githubusercontent.com/19944861/86534449-1f5dae00-bf0b-11ea-8a4b-85cb98b734b3.png)

**Comment by redchenjs** [comment]
目前master切换到5.4+了，4.9+内核版本我留了一个branch，试试checkout到[branch:linux-4.9](https://github.com/redchenjs/mt762x-wm8960/tree/linux-4.9)

**Comment by yqboy** [comment]
感谢回复,问题解决了,dts 里面的 声卡名 没改回来, 不过  sox 可以播放, madplay 不能用,这是啥问题???

**Comment by redchenjs** [comment]
> 感谢回复,问题解决了,dts 里面的 声卡名 没改回来, 不过 sox 可以播放, madplay 不能用,这是啥问题???

madplay-alsa测试是可用的，确认下软件包选择的是alsa版本
