### ISSUE TITLE
Error compilation on OpenWRT/v19.07.6

### ISSUE THREAD

**Issue by googolgl** [redchenjs/mt76x8-wm8960#6]
make[4]: Entering directory '/home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/linux-4.14.215'
  CC [M]  /home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/mt762x-wm8960/mt762x-wm8960.o
/home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/mt762x-wm8960/mt762x-wm8960.c:44:23: error: expected ')' before '(' token
     DAILINK_COMP_ARRAY(COMP_CPU("ralink-i2s")),
                       ^
/home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/mt762x-wm8960/mt762x-wm8960.c:54:9: error: implicit declaration of function 'SND_SOC_DAILINK_REG'; did you mean 'SND_SOC_DAPM_REG'? [-Werror=implicit-function-declaration]
         SND_SOC_DAILINK_REG(codec),
         ^~~~~~~~~~~~~~~~~~~
         SND_SOC_DAPM_REG
/home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/mt762x-wm8960/mt762x-wm8960.c:54:29: error: 'codec' undeclared here (not in a function); did you mean 'cdev'?
         SND_SOC_DAILINK_REG(codec),
                             ^~~~~
                             cdev
/home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/mt762x-wm8960/mt762x-wm8960.c: In function 'mt762x_wm8960_machine_probe':
/home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/mt762x-wm8960/mt762x-wm8960.c:81:5: error: implicit declaration of function 'for_each_card_prelinks'; did you mean 'for_each_irq_nr'? [-Werror=implicit-function-declaration]
     for_each_card_prelinks(card, i, dai_link) {
     ^~~~~~~~~~~~~~~~~~~~~~
     for_each_irq_nr
/home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/mt762x-wm8960/mt762x-wm8960.c:81:47: error: expected ';' before '{' token
     for_each_card_prelinks(card, i, dai_link) {
                                               ^
/home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/mt762x-wm8960/mt762x-wm8960.c:95:47: error: expected ';' before '{' token
     for_each_card_prelinks(card, i, dai_link) {
                                               ^
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:327: /home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/mt762x-wm8960/mt762x-wm8960.o] Error 1
make[4]: *** [Makefile:1550: _module_/home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/mt762x-wm8960] Error 2
make[4]: Leaving directory '/home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/linux-4.14.215'
make[3]: *** [Makefile:54: /home/googol/OpenWRT/v19.07.6/build_dir/target-mipsel_24kc_musl/linux-ramips_mt76x8/mt762x-wm8960/.built] Error 2
make[3]: Leaving directory '/home/googol/OpenWRT/v19.07.6/package/kernel/mt762x-wm8960'
time: package/kernel/mt762x-wm8960/compile#1.01#0.28#1.14
make[2]: *** [package/Makefile:113: package/kernel/mt762x-wm8960/compile] Error 2
make[2]: Leaving directory '/home/googol/OpenWRT/v19.07.6'
make[1]: *** [package/Makefile:107: /home/googol/OpenWRT/v19.07.6/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/googol/OpenWRT/v19.07.6'
make: *** [/home/googol/OpenWRT/v19.07.6/include/toplevel.mk:227: world] Error 2

**Comment by redchenjs** [comment]
Hi @googolgl, for kernel v4.14, please use [branch:linux-4.9](https://github.com/redchenjs/mt762x-wm8960/tree/linux-4.9)

**Comment by googolgl** [comment]
Thank you very much. 
Now everything worked out.
