### ISSUE TITLE
mono sound fault

### ISSUE THREAD

**Issue by hnhkj** [redchenjs/mt76x8-wm8960#7]
Hi redchenjs

When I running follow command. I get a error message. I will how to do let it support mono sound? or it's dont support mono sound?

```
root@OpenWrt:~/wav# arecord -Dhw:0 -f cd -r 8000 -c 1 -t wav /tmp/rec.wav
Recording WAVE '/tmp/rec.wav' : Signed 16 bit Little Endian, Rate 8000 Hz, Mono
arecord: set_params:1349: Channels count non available
```

**Comment by redchenjs** [comment]
Hi @hnhkj,

The number of channels is limited by [`ralink-i2s`](https://github.com/openwrt/openwrt/blob/ec6293febc244d187e71a6e54f44920be679cde4/target/linux/ramips/patches-5.4/0048-asoc-add-mt7620-support.patch#L577) driver, it only supports 2-channel mode.

![Screenshot](https://user-images.githubusercontent.com/9910809/116032524-75663280-a692-11eb-85a2-4565193c727b.png)

You can use these commands to fill two channels with data from the left or right ADC:
```
amixer sset "ALC Function" "Left"
amixer sset "ADC Data Output Select" "Left Data = Left ADC;  Right Data = Left ADC"
```

**Comment by hnhkj** [comment]
I know your mean. MT7688 only support two channel.
Now, I know speaker-test dont working normally. It's play noise. maybe It's channel's problem. If we make a Virtual single channel. if we use play left channel. then fill 0 to right channel or mute right. If so, application can working normally.

**Comment by hnhkj** [comment]
thanks

**Comment by redchenjs** [comment]
Hi @hnhkj,

You can use this patch to enable mono sound by hacking the `ralink-i2s` driver.

[999-ralink-i2s-mono-sound.zip](https://github.com/redchenjs/mt762x-wm8960/files/6381892/999-ralink-i2s-mono-sound.zip)

According to your kernel version, put the patch file into `target/linux/ramips/patches-5.4` or `target/linux/ramips/patches-5.10`

**Comment by funful** [comment]
Hi,redchenjs
I have a problem,Here is the error message.


root@OpenWrt:~#
root@OpenWrt:~#
root@OpenWrt:~#
root@OpenWrt:~# cd /root/
root@OpenWrt:~# madplay gamestartup.mp3
MPEG Audio Decoder 0.15.2 (beta) - Copyright (C) 2000-2004 Robert Leslie et al.
ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card
audio: No such file or directory
root@OpenWrt:~#
root@OpenWrt:~#
root@OpenWrt:~#

**Comment by PolyLin** [comment]
hi， @redchenjs , 我在linux-4.14.95上使用了你提供的这个path文件，发现在使用ffmpeg播放单声道的时候声音不正常(ffmpeg -v debug -re -i notfound.wav -ar 8000 -ac 1 -f alsa hw:0), 使用双声道播放(-ac 2)就正常了。请问是不是在4.14的kernel上还需要做什么修改？或者是其他的原因？
