### ISSUE TITLE
default group /dev/snd/*

### ISSUE THREAD

**Issue by hnhkj** [redchenjs/mt76x8-wm8960#8]
I get snd devices. and I checked that defaut is audio group. It's not root. 

```
root@OpenWrt:~# ll /dev/snd/*
crwxrwxrwx    1 root     audio      116,   0 Apr 26 09:18 /dev/snd/controlC0
crwxrwxrwx    1 root     audio      116,  24 Apr 26 09:18 /dev/snd/pcmC0D0c
crwxrwxrwx    1 root     audio      116,  16 Apr 26 09:18 /dev/snd/pcmC0D0p
crwxrwxrwx    1 root     audio      116,  33 Apr 26 09:18 /dev/snd/timer
```

**Comment by hnhkj** [comment]
I use follow openwrt version to compile. OpenWrt 21.02-SNAPSHOT, r15879+2-3b6c93298c

**Comment by redchenjs** [comment]
It doesn't matter. On my PC, the device group is also `audio`.

![20210426182858](https://user-images.githubusercontent.com/9910809/116070008-a9efe380-a6be-11eb-864d-aa806845c887.png)
